### ISSUE TITLE
live demo doesn't work

### ISSUE THREAD

**Issue by rhizohm** [ethjs/ethjs-ens#7]
It always throws "There was a problem: [ethjs-contract] while formatting incoming raw call data "0x" Error: [ethjs-abi] while decoding address data, invalid address data, invalid byte length 0"

**Comment by flyswatter** [comment]
Ah, sorry, currently only works on Ropsten test net.  Fixing now...

**Comment by flyswatter** [comment]
That should fix it, let me know!

**Comment by rhizohm** [comment]
Nice works now. Thanks!
